import*as T from'three';
class RNG{constructor(s=42){this.s=s}next(){this.s=(this.s*1664525+1013904223)&0xffffffff;return(this.s>>>0)/0xffffffff}f(a=0,b=1){return a+this.next()*(b-a)}i(a,b){return Math.floor(this.f(a,b+1))}p(a){return a[Math.floor(this.next()*a.length)]}}
const R=new RNG(2024);
const S=new T.Scene();S.background=new T.Color(0x87CEEB);S.fog=new T.Fog(0x87CEEB,120,250);
const cam=new T.PerspectiveCamera(65,innerWidth/innerHeight,0.5,500);
const ren=new T.WebGLRenderer({antialias:true});ren.setSize(innerWidth,innerHeight);ren.setPixelRatio(Math.min(devicePixelRatio,2));ren.shadowMap.enabled=true;document.body.appendChild(ren.domElement);
S.add(new T.AmbientLight(0x8899aa,0.6));const sun=new T.DirectionalLight(0xffeedd,1.2);sun.position.set(50,80,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-100;sun.shadow.camera.right=100;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-100;sun.shadow.camera.near=0.5;sun.shadow.camera.far=300;S.add(sun);S.add(new T.HemisphereLight(0x88bbff,0x445522,0.4));
addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();ren.setSize(innerWidth,innerHeight)});
const TW=14;const tp=[];for(let i=0;i<120;i++){const t=(i/120)*Math.PI*2;const rx=60+15*Math.cos(2*t)+8*Math.sin(3*t);const ry=40+10*Math.cos(3*t)+5*Math.sin(2*t);tp.push(new T.Vector3(rx,2*Math.sin(3*t)+1.5*Math.cos(5*t),ry))}
const CV=new T.CatmullRomCurve3(tp,true,'catmullrom',0.5);
function strip(vf,m){const v=[],idx=[];for(let i=0;i<=240;i++){const t=i/240;const p=CV.getPointAt(t);const tg=CV.getTangentAt(t);const n=new T.Vector3(-tg.z,0,tg.x).normalize();const a=vf(n,p,1),b=vf(n,p,-1);v.push(a.x,a.y,a.z,b.x,b.y,b.z);if(i<240){const b=i*2;idx.push(b,b+1,b+2,b+1,b+3,b+2)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();const m2=new T.Mesh(g,m);m2.receiveShadow=true;S.add(m2)}
strip((n,p)=>{const a=p.clone().add(n.clone().multiplyScalar(TW/2));return a},new T.MeshStandardMaterial({color:0x555555,roughness:0.8}));
[-1,1].forEach(sd=>strip((n,p,s)=>{const o=TW/2*sd;const a=p.clone().add(n.clone().multiplyScalar(o+0.6*s*sd));a.y=p.y-0.1;return a},new T.MeshStandardMaterial({color:sd===1?0xff4444:0xffffff})));
for(let i=0;i<120;i+=3){const t=i/120;const p=CV.getPointAt(t);const tg=CV.getTangentAt(t);const n=new T.Vector3(-tg.z,0,tg.x).normalize();[-1,1].forEach(sd=>{const b=new T.Mesh(new T.BoxGeometry(1.5,1.8,1.5),new T.MeshStandardMaterial({color:sd===1?0xffaa00:0x00aaff}));const pos=p.clone().add(n.clone().multiplyScalar(TW/2*sd+2.5));pos.y+=0.9;b.position.copy(pos);b.castShadow=true;b.receiveShadow=true;S.add(b)})}
const gg=new T.PlaneGeometry(400,400,20,20);const gv=gg.attributes.position;for(let i=0;i<gv.count;i++)gv.setZ(i,R.f(-2,2));gg.computeVertexNormals();const gm=new T.Mesh(gg,new T.MeshStandardMaterial({color:0x55aa33,roughness:1}));gm.rotation.x=-Math.PI/2;gm.position.y=-1;gm.receiveShadow=true;S.add(gm);
function tree(x,z,h){const g=new T.Group();const tk=new T.Mesh(new T.CylinderGeometry(0.4,0.6,h*0.4,6),new T.MeshStandardMaterial({color:0x885522}));tk.position.y=h*0.2;tk.castShadow=true;g.add(tk);[0,1,2].forEach(i=>{const ch=h*(0.3-i*0.05);const cr=(1.8-i*0.4)*(h/5);const c=new T.Mesh(new T.ConeGeometry(cr,ch,7),new T.MeshStandardMaterial({color:[0x228833,0x33aa44,0x229944][i],roughness:0.9}));c.position.y=h*0.4+i*ch*0.4;c.castShadow=true;g.add(c)});g.position.set(x,0,z);return g}
for(let i=0;i<80;i++){const a=R.f(0,Math.PI*2);const d=R.f(30,120);const x=Math.cos(a)*d;const z=Math.sin(a)*d;let cl=false;for(let t=0;t<1;t+=0.02){const p=CV.getPointAt(t);if(Math.hypot(x-p.x,z-p.z)<TW/2+3){cl=true;break}}if(!cl)S.add(tree(x,z,R.f(3,7)))}
for(let i=0;i<15;i++){const a=(i/15)*Math.PI*2+R.f(-0.1,0.1);const d=140+R.f(20,40);const h=R.f(20,50);const r=R.f(15,30);const mt=new T.Mesh(new T.ConeGeometry(r,h,5+R.i(0,3)),new T.MeshStandardMaterial({color:R.p([0x667755,0x556644,0x668866,0x557755]),roughness:1}));mt.position.set(Math.cos(a)*d,h/2-5,Math.sin(a)*d);mt.castShadow=true;S.add(mt);if(h>30){const sn=new T.Mesh(new T.ConeGeometry(r*0.35,h*0.25,5),new T.MeshStandardMaterial({color:0xeeeeff}));sn.position.set(Math.cos(a)*d,h-10,Math.sin(a)*d);S.add(sn)}}
const clds=[];for(let i=0;i<12;i++){const cg=new T.Group();for(let j=0;j<R.i(3,6);j++){const p=new T.Mesh(new T.SphereGeometry(R.f(3,6),6,5),new T.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:0.85}));p.position.set(R.f(-5,5),R.f(-1,1),R.f(-3,3));p.scale.y=0.5;cg.add(p)}cg.position.set(R.f(-150,150),R.f(30,50),R.f(-150,150));cg.userData.spd=R.f(0.5,2);S.add(cg);clds.push(cg)}
const SP=CV.getPointAt(0);const STG=CV.getTangentAt(0);const SN=new T.Vector3(-STG.z,0,STG.x).normalize();
const cv2=document.createElement('canvas');cv2.width=128;cv2.height=32;const cx2=cv2.getContext('2d');for(let x=0;x<128;x+=8)for(let y=0;y<32;y+=8){cx2.fillStyle=((x/8+y/8)%2===0)?'#fff':'#222';cx2.fillRect(x,y,8,8)}
const ct2=new T.CanvasTexture(cv2);ct2.magFilter=T.NearestFilter;const ck=new T.Mesh(new T.PlaneGeometry(TW,3),new T.MeshStandardMaterial({map:ct2}));ck.rotation.x=-Math.PI/2;ck.position.copy(SP);ck.position.y+=0.1;ck.rotation.z=Math.atan2(STG.x,STG.z);S.add(ck);
[-1,1].forEach(sd=>{const pl=new T.Mesh(new T.BoxGeometry(1.2,6,1.2),new T.MeshStandardMaterial({color:0xff4400}));pl.position.copy(SP.clone().add(SN.clone().multiplyScalar(TW/2*sd)));pl.position.y+=3;pl.castShadow=true;S.add(pl)});
const tb2=new T.Mesh(new T.BoxGeometry(TW+2,1.2,1.2),new T.MeshStandardMaterial({color:0xffcc00,emissive:0x442200}));tb2.position.set(SP.x,6.5,SP.z);tb2.rotation.y=Math.atan2(STG.x,STG.z);tb2.castShadow=true;S.add(tb2);
function mkKart(col){const k=new T.Group();const bm=new T.MeshStandardMaterial({color:col,roughness:0.3,metalness:0.5});const body=new T.Mesh(new T.BoxGeometry(1.4,0.6,2.4),bm);body.position.y=0.55;body.castShadow=true;k.add(body);const hood=new T.Mesh(new T.BoxGeometry(1.0,0.3,0.8),bm);hood.position.set(0,0.6,-1.2);hood.castShadow=true;k.add(hood);const ck3=new T.Mesh(new T.BoxGeometry(1.0,0.5,0.9),new T.MeshStandardMaterial({color:0x222222,roughness:0.8}));ck3.position.set(0,0.85,0.2);k.add(ck3);const hd=new T.Mesh(new T.SphereGeometry(0.35,6,5),new T.MeshStandardMaterial({color:0xffcc88}));hd.position.set(0,1.25,0.2);k.add(hd);const hm=new T.Mesh(new T.SphereGeometry(0.38,6,4,0,Math.PI*2,0,Math.PI*0.6),new T.MeshStandardMaterial({color:col,roughness:0.2,metalness:0.6}));hm.position.set(0,1.3,0.2);k.add(hm);const sm=new T.MeshStandardMaterial({color:0x222222});const sp2=new T.Mesh(new T.BoxGeometry(1.4,0.08,0.3),sm);sp2.position.set(0,1.1,1.0);k.add(sp2);[-0.5,0.5].forEach(xo=>{const s=new T.Mesh(new T.BoxGeometry(0.08,0.5,0.08),sm);s.position.set(xo,0.85,1.0);k.add(s)});k.userData.wheels=[];[{x:-0.8,z:-0.85,st:1},{x:0.8,z:-0.85,st:1},{x:-0.8,z:0.85,st:0},{x:0.8,z:0.85,st:0}].forEach(wp=>{const wg=new T.Group();const tire=new T.Mesh(new T.CylinderGeometry(0.35,0.35,0.3,8),new T.MeshStandardMaterial({color:0x111111,roughness:0.9}));tire.rotation.x=Math.PI/2;tire.castShadow=true;wg.add(tire);const rim=new T.Mesh(new T.CylinderGeometry(0.2,0.2,0.32,6),new T.MeshStandardMaterial({color:0xcccccc,metalness:0.8}));rim.rotation.x=Math.PI/2;wg.add(rim);wg.position.set(wp.x,0.35,wp.z);k.add(wg);k.userData.wheels.push({mesh:wg,steer:wp.st})});[-0.3,0.3].forEach(xo=>{const ex=new T.Mesh(new T.CylinderGeometry(0.06,0.08,0.5,6),new T.MeshStandardMaterial({color:0x666666,metalness:0.8}));ex.position.set(xo,0.4,1.3);k.add(ex)});return k}
class Kart{constructor(col,ot=0){this.mesh=mkKart(col);this.t=ot;this.spd=0;this.str=0;this.lat=0;this.dAng=0;this.drift=false;this.boost=100;this.lap=0;this.lProg=0;this.lT=ot;this.fin=false;this.fT=0;this.pos=1;this.mesh.visible=false;S.add(this.mesh)}reset(){this.t=0;this.spd=0;this.str=0;this.lat=0;this.dAng=0;this.drift=false;this.boost=100;this.lap=0;this.lProg=0;this.lT=0;this.fin=false;this.fT=0;this.updPos()}updPos(){const p=CV.getPointAt(this.t);const tg=CV.getTangentAt(this.t);const n=new T.Vector3(-tg.z,0,tg.x).normalize();const pos=p.clone().add(n.clone().multiplyScalar(this.lat));this.mesh.position.copy(pos);this.mesh.rotation.y=Math.atan2(tg.x,tg.z)+this.dAng;const wr=this.spd*0.5;this.mesh.userData.wheels.forEach(w=>{w.mesh.children[0].rotation.z=wr;w.mesh.children[1].rotation.z=wr;if(w.steer)w.mesh.rotation.y=this.str*0.3});sun.position.set(pos.x+50,80,pos.z+30);sun.target.position.copy(pos);sun.target.updateMatrixWorld()}}
const karts=[];const player=new Kart(0xff3300,0);karts.push(player);const aiCols=[0x0066ff,0x00cc44,0xcc00cc,0xffaa00];for(let i=0;i<4;i++){const ai=new Kart(aiCols[i],-0.05*(i+1));ai.aiSpd=0.15+R.f(0,0.08);ai.aiOff=R.f(-3,3);karts.push(ai)}
const K={};addEventListener('keydown',e=>{K[e.code]=true;e.preventDefault()});addEventListener('keyup',e=>{K[e.code]=false});
let gMode='menu',rTime=0,cdTmr=0,cdPhase=0,demoIdx=0,demoTimer=0,demoKey=null,isDemo=false;
const DK=[{c:'KeyW',d:50},{c:null,d:30},{c:'ArrowRight',d:40},{c:'KeyW',d:60},{c:null,d:30},{c:'ArrowLeft',d:50},{c:'KeyW',d:80},{c:'Space',d:40},{c:'KeyW',d:100}];
function updDemo(dt){if(gMode!=='racing')return;K['KeyW']=false;K['KeyS']=false;K['KeyA']=false;K['KeyD']=false;K['ArrowUp']=false;K['ArrowDown']=false;K['ArrowLeft']=false;K['ArrowRight']=false;K['ShiftLeft']=false;K['Space']=false;if(demoKey)K[demoKey]=true;demoTimer+=dt;const cur=DK[demoIdx%DK.length];if(demoTimer>cur.d){demoTimer=0;demoIdx++;demoKey=DK[demoIdx%DK.length].c}}
function startRace(demo){gMode='countdown';document.getElementById('ov').classList.add('h');cdTmr=0;cdPhase=0;karts.forEach(k=>k.reset());player.mesh.visible=true;rTime=0;isDemo=demo;if(demo){demoIdx=0;demoTimer=0;demoKey=DK[0].c}document.getElementById('cd').style.display='block';cInit=false}
function updPhys(kart,dt,pl){if(kart.fin)return;let acc=0,str=0,brk=false,booster=false,drifter=false;if(pl){if(K['KeyW']||K['ArrowUp'])acc=1;if(K['KeyS']||K['ArrowDown'])brk=true;if(K['KeyA']||K['ArrowLeft'])str=-1;if(K['KeyD']||K['ArrowRight'])str=1;if(K['ShiftLeft']||K['ShiftRight'])booster=true;if(K['Space'])drifter=true}else{acc=kart.aiSpd||0.15;const at=(kart.t+0.02)%1;const ctg=CV.getTangentAt(kart.t);const atg=CV.getTangentAt(at);const cr=ctg.x*atg.z-ctg.z*atg.x;str=cr>0?-0.5:0.5;kart.aiWb=Math.sin(rTime*2+kart.aiOff)*0.3;str+=kart.aiWb}const ms=kart.drift?8:12;const bm=booster&&kart.boost>0?1.8:1;if(acc>0){kart.spd+=(acc*30*bm)*dt;if(booster)kart.boost=Math.max(0,kart.boost-20*dt)}else{kart.spd*=(1-5*dt)}if(brk)kart.spd*=(1-15*dt);kart.spd=Math.max(-4,Math.min(ms,kart.spd));const ss=3.5;if(Math.abs(kart.spd)>0.5){const sf=Math.min(1,Math.abs(kart.spd)/3)*ss;if(kart.drift){kart.dAng+=str*dt*2.5;kart.dAng=Math.max(-0.5,Math.min(0.5,kart.dAng))}else{kart.str+=(str*sf-kart.str)*8*dt;kart.dAng*=0.9}}else{kart.str*=0.9}kart.drift=drifter&&Math.abs(kart.spd)>3&&Math.abs(str)>0;if(!booster)kart.boost=Math.min(100,kart.boost+5*dt);const fs=kart.spd*dt;kart.t=(kart.t+fs*0.002)%1;if(kart.t<0)kart.t+=1;kart.lat+=kart.str*fs*0.3;kart.lat=Math.max(-TW/2+1,Math.min(TW/2-1,kart.lat));const pt=kart.lT;if(pt>0.9&&kart.t<0.1){kart.lap++;if(kart.lap>=1&&!kart.fin){kart.fin=true;kart.fT=rTime}}kart.lT=kart.t;kart.lProg=kart.t;kart.updPos()}
function updRace(){const so=karts.map(k=>({k,pr:k.lap+k.lProg}));so.sort((a,b)=>b.pr-a.pr);so.forEach((s,i)=>s.k.pos=i+1);const le=document.getElementById('lap-value'),se=document.getElementById('speed-value'),sb=document.getElementById('sb'),te=document.getElementById('timer-value'),pe=document.getElementById('pos-value');le.textContent=Math.min(player.lap,1)+'/'+1;se.textContent=Math.abs(player.spd*10).toFixed(0);sb.style.width=Math.abs(player.spd/12*100)+'%';const m=Math.floor(rTime/60),s=(rTime%60).toFixed(1);te.textContent=m+':'+s.padStart(4,'0');pe.textContent=player.pos+'/'+karts.length}
let cInit=false;const cCur=new T.Vector3(),cLook=new T.Vector3();
function updCam(dt){const tp=player.mesh.position.clone();const h=player.mesh.rotation.y;const dp=tp.clone();dp.x+=Math.sin(h)*8;dp.z-=Math.cos(h)*8;dp.y+=5;if(!cInit){cCur.copy(dp);cLook.copy(tp.clone().add(new T.Vector3(0,1,-3)));cInit=true}const lr=1-Math.exp(-4*dt);cCur.lerp(dp,lr);cLook.lerp(tp.clone().add(new T.Vector3(0,1,-3)),lr);cam.position.copy(cCur);cam.lookAt(cLook)}
const ovEl=document.getElementById('ov'),cdEl=document.getElementById('cd');
document.getElementById('btn-go').addEventListener('click',()=>startRace(false));
document.getElementById('btn-demo').addEventListener('click',()=>startRace(true));
let lt=0;function loop(t){requestAnimationFrame(loop);const dt=Math.min((t-lt)/1000,0.05);lt=t;if(gMode==='menu'){ren.render(S,cam);return}if(gMode==='countdown'||(gMode==='racing'&&cdPhase>0)){cdTmr+=dt;const nums=['3','2','1','GO!'];if(cdTmr<1){cdPhase=0;cdEl.textContent=nums[0]}else if(cdTmr<2){cdPhase=1;cdEl.textContent=nums[1]}else if(cdTmr<3){cdPhase=2;cdEl.textContent=nums[2]}else if(cdTmr<4){cdPhase=3;cdEl.textContent=nums[3]}else{cdEl.style.display='none';gMode==='demo'?gMode='demo':gMode='racing'}ren.render(S,cam);return}if(gMode==='racing'||gMode==='demo'){rTime+=dt;if(gMode==='demo')updDemo(dt);updPhys(player,dt,true);karts.forEach((k,i)=>{if(i===0)return;updPhys(k,dt,false)});updRace();if(player.fin){const m=Math.floor(player.fT/60),s=(player.fT%60).toFixed(1);ovEl.classList.remove('h');ovEl.querySelector('h2').textContent='RACE COMPLETE! '+m+':'+s.padStart(4,'0');ovEl.querySelector('.bs').textContent='RACE AGAIN';gMode='finished'}}clds.forEach(c=>{c.position.x+=c.userData.spd*dt;if(c.position.x>200)c.position.x=-200});updCam(dt);ren.render(S,cam)}
loop(0);